application:
    database:
        url: jdbc:mysql://localhost:3306/ancloud_cloud
        #url:jdbc:h2:file:./temp/ancloud
        username: ancloud
        password: 0af3b424
        driverClassName: com.mysql.jdbc.Driver
        #driverClassName: org.h2.Driver
        dialect: org.hibernate.dialect.MySQL5Dialect
        #dialect:org.hibernate.dialect.H2Dialect
        showSql: true
    cp:
        maxActive: 96
        maxIdle: 16
        minIdle: 0
        maxWaitMillis: 60000
# none, create, drop-and-create, drop
    jpa:
        schemaGeneration: none
        schemaScriptGeneration: none
        schemaScriptGenerationCreateTarget: C:/create-script.sql
        schemaScriptGenerationDropTarget: C:/drop-script.sql
    security:
        maxSession: 1
        sessionExpiredUrl: /api/auth/expire
        permitAlls:
            - /api/auth/check-license**/*
            - /api/parent/register**
            - /api/gateway/register**
        jwtTokenHeader: Authorization
        jwtTokenSecret: VEdiOCM5e1soNSFKZV1eVw==
        jwtTokenExpiration: 604800

################### Spring boot Configuration ##########################
server:
    port : 9000
spring:
    redis:
        host : localhost
        #host : 192.168.50.253
        port : 6379
    jpa:
        open-in-view: true
    main:
        web-environment: true
    data:
        redis:
            repositories:
                enabled: false
    mvc:
        favicon:
            enabled: false
flyway:
    enabled: true
    validate-on-migrate: true
security:
    filter-order: 5