spring:
    application:
        name: edge
server:
    port: 80
zuul:
    routes:
        jsf:
            path: /jsf/**
            url: http://localhost:8080
ribbon:
    eureka:
        enabled: false