INSERT INTO bb_account(id,userName,password,accountNonExpired,accountNonLocked,credentialsNonExpired,enabled) VALUES(1,'admin','$2a$04$FQyfe75OhZGlwnm7w/R76.9xtKmLu0MZYn22oRGVMShzFKu5N0PKS',true,true,true,true);
INSERT INTO bb_role(roleCode) VALUES('administrator');
INSERT INTO bb_permission(permissionCode) VALUES('dashboard');
INSERT INTO bb_rolePermission(roleCode,permissionCode) VALUES('administrator','dashboard');
INSERT INTO bb_accountrole(userName,roleCode) VALUES('admin','administrator');
INSERT INTO bb_accountpermission(userName,permissionCode) VALUES('admin','dashboard');
INSERT INTO bb_navigationlink(messageCode,code,icon,path,project_id,parent_code,groupid,groupindex,itemindex,version) VALUES('sc.common.00011','sc.common.00011','fa fa-gears','',null,null,'','1',1,0);
INSERT INTO bb_navigationlink(messageCode,code,icon,path,project_id,parent_code,groupid,groupindex,itemindex,version) VALUES('sc.navigationlink.00001','sc.navigationlink.00001','fa fa-link','/navigation-link',null,'sc.common.00011','1','1.1',2,0);
INSERT INTO bb_navigationlink(messageCode,code,icon,path,project_id,parent_code,groupid,groupindex,itemindex,version) VALUES('sc.message.00001','sc.message.00001','fa fa-database','/message',null,'sc.common.00011','1','1.2',3,0);
INSERT INTO bb_navigationlink(messageCode,code,icon,path,project_id,parent_code,groupid,groupindex,itemindex,version) VALUES('sc.account.00001','sc.account.00001','fa fa-user','/account',null,'sc.common.00011','1','1.3',4,0);
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','af-ZA','','Afrikaans - South Africa','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','sq-AL','','Albanian - Albania','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','ar-DZ','','Arabic - Algeria','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','ar-BH','','Arabic - Bahrain','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','ar-EG','','Arabic - Egypt','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','ar-IQ','','Arabic - Iraq','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','ar-JO','','Arabic - Jordan','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','ar-KW','','Arabic - Kuwait','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','ar-LB','','Arabic - Lebanon','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','ar-LY','','Arabic - Libya','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','ar-MA','','Arabic - Morocco','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','ar-OM','','Arabic - Oman','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','ar-QA','','Arabic - Qatar','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','ar-SA','','Arabic - Saudi Arabia','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','ar-SY','','Arabic - Syria','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','ar-TN','','Arabic - Tunisia','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','ar-AE','','Arabic - United Arab Emirates','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','ar-YE','','Arabic - Yemen','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','hy-AM','','Armenian - Armenia','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','Cy-az-AZ','','Azeri (Cyrillic) - Azerbaijan','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','Lt-az-AZ','','Azeri (Latin) - Azerbaijan','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','eu-ES','','Basque - Basque','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','be-BY','','Belarusian - Belarus','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','bg-BG','','Bulgarian - Bulgaria','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','ca-ES','','Catalan - Catalan','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','zh-CN','','Chinese - China','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','zh-HK','','Chinese - Hong Kong SAR','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','zh-MO','','Chinese - Macau SAR','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','zh-SG','','Chinese - Singapore','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','zh-TW','','Chinese - Taiwan','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','zh-CHS','','Chinese (Simplified)','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','zh-CHT','','Chinese (Traditional)','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','hr-HR','','Croatian - Croatia','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','cs-CZ','','Czech - Czech Republic','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','da-DK','','Danish - Denmark','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','div-MV','','Dhivehi - Maldives','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','nl-BE','','Dutch - Belgium','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','nl-NL','','Dutch - The Netherlands','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','en-AU','','English - Australia','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','en-BZ','','English - Belize','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','en-CA','','English - Canada','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','en-CB','','English - Caribbean','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','en-IE','','English - Ireland','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','en-JM','','English - Jamaica','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','en-NZ','','English - New Zealand','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','en-PH','','English - Philippines','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','en-ZA','','English - South Africa','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','en-TT','','English - Trinidad and Tobago','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','en-GB','','English - United Kingdom','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','en-US','','English - United States','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','en-ZW','','English - Zimbabwe','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','et-EE','','Estonian - Estonia','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','fo-FO','','Faroese - Faroe Islands','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','fa-IR','','Farsi - Iran','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','fi-FI','','Finnish - Finland','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','fr-BE','','French - Belgium','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','fr-CA','','French - Canada','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','fr-FR','','French - France','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','fr-LU','','French - Luxembourg','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','fr-MC','','French - Monaco','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','fr-CH','','French - Switzerland','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','gl-ES','','Galician - Galician','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','ka-GE','','Georgian - Georgia','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','de-AT','','German - Austria','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','de-DE','','German - Germany','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','de-LI','','German - Liechtenstein','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','de-LU','','German - Luxembourg','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','de-CH','','German - Switzerland','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','el-GR','','Greek - Greece','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','gu-IN','','Gujarati - India','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','he-IL','','Hebrew - Israel','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','hi-IN','','Hindi - India','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','hu-HU','','Hungarian - Hungary','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','is-IS','','Icelandic - Iceland','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','id-ID','','Indonesian - Indonesia','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','it-IT','','Italian - Italy','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','it-CH','','Italian - Switzerland','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','ja-JP','','Japanese - Japan','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','kn-IN','','Kannada - India','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','kk-KZ','','Kazakh - Kazakhstan','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','kok-IN','','Konkani - India','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','ko-KR','','Korean - Korea','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','ky-KZ','','Kyrgyz - Kazakhstan','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','lv-LV','','Latvian - Latvia','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','lt-LT','','Lithuanian - Lithuania','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','mk-MK','','Macedonian (FYROM)','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','ms-BN','','Malay - Brunei','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','ms-MY','','Malay - Malaysia','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','mr-IN','','Marathi - India','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','mn-MN','','Mongolian - Mongolia','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','nb-NO','','Norwegian (Bokmål) - Norway','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','nn-NO','','Norwegian (Nynorsk) - Norway','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','pl-PL','','Polish - Poland','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','pt-BR','','Portuguese - Brazil','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','pt-PT','','Portuguese - Portugal','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','pa-IN','','Punjabi - India','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','ro-RO','','Romanian - Romania','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','ru-RU','','Russian - Russia','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','sa-IN','','Sanskrit - India','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','Cy-sr-SP','','Serbian (Cyrillic) - Serbia','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','Lt-sr-SP','','Serbian (Latin) - Serbia','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','sk-SK','','Slovak - Slovakia','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','sl-SI','','Slovenian - Slovenia','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','es-AR','','Spanish - Argentina','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','es-BO','','Spanish - Bolivia','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','es-CL','','Spanish - Chile','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','es-CO','','Spanish - Colombia','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','es-CR','','Spanish - Costa Rica','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','es-DO','','Spanish - Dominican Republic','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','es-EC','','Spanish - Ecuador','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','es-SV','','Spanish - El Salvador','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','es-GT','','Spanish - Guatemala','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','es-HN','','Spanish - Honduras','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','es-MX','','Spanish - Mexico','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','es-NI','','Spanish - Nicaragua','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','es-PA','','Spanish - Panama','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','es-PY','','Spanish - Paraguay','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','es-PE','','Spanish - Peru','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','es-PR','','Spanish - Puerto Rico','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','es-ES','','Spanish - Spain','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','es-UY','','Spanish - Uruguay','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','es-VE','','Spanish - Venezuela','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','sw-KE','','Swahili - Kenya','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','sv-FI','','Swedish - Finland','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','sv-SE','','Swedish - Sweden','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','syr-SY','','Syriac - Syria','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','ta-IN','','Tamil - India','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','tt-RU','','Tatar - Russia','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','te-IN','','Telugu - India','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','th-TH','','Thai - Thailand','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','tr-TR','','Turkish - Turkey','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','uk-UA','','Ukrainian - Ukraine','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','ur-PK','','Urdu - Pakistan','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','Cy-uz-UZ','','Uzbek (Cyrillic) - Uzbekistan','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','Lt-uz-UZ','','Uzbek (Latin) - Uzbekistan','');
INSERT INTO bb_resource(category, key,messageKey, value, resourceGroup) VALUES('language','vi-VN','','Vietnamese - Vietnam','');
INSERT INTO bb_message(key, basename, language, country, variant, message) VALUES('sc.sys.00001','sc','en','US','','Hello!');
INSERT INTO bb_message(key, basename, language, country, variant, message) VALUES('sc.sys.00001','sc','vi','VN','','Xin chào!');
INSERT INTO bb_message(key, basename, language, country, variant, message) VALUES('mod.sys','mod','en','US','','System');
INSERT INTO bb_message(key, basename, language, country, variant, message) VALUES('mod.sys','mod','vi','VN','','Hệ thống');
INSERT INTO bb_message(key, basename, language, country, variant, message) VALUES('err.sys.00001','err','en','US','','Invalid username, email or password');
INSERT INTO bb_message(key, basename, language, country, variant, message) VALUES('sc.sys.00001','sc','en','US','','Ejukate');
INSERT INTO bb_message(key, basename, language, country, variant, message) VALUES('sc.sys.00001','sc','vi','VN','','Ejukate');
INSERT INTO bb_message(key, basename, language, country, variant, message) VALUES('sc.sys.00002','sc','en','US','','Eju');
INSERT INTO bb_message(key, basename, language, country, variant, message) VALUES('sc.sys.00002','sc','vi','VN','','Eju');
INSERT INTO bb_message(key, basename, language, country, variant, message) VALUES('sc.sys.00003','sc','en','US','','Sign in');
INSERT INTO bb_message(key, basename, language, country, variant, message) VALUES('sc.sys.00004','sc','en','US','','Sign out');
INSERT INTO bb_message(key, basename, language, country, variant, message) VALUES('sc.sys.00005','sc','en','US','','Forgot password?');
INSERT INTO bb_message(key, basename, language, country, variant, message) VALUES('sc.sys.00006','sc','en','US','','Register now');
INSERT INTO bb_message(key, basename, language, country, variant, message) VALUES('sc.sys.00007','sc','en','US','','Don''t have a membership yet?');
INSERT INTO bb_message(key, basename, language, country, variant, message) VALUES('sc.sys.00008','sc','en','US','','Remember me');
INSERT INTO bb_message(key, basename, language, country, variant, message) VALUES('sc.sys.00009','sc','en','US','','Sign in using Facebook');
INSERT INTO bb_message(key, basename, language, country, variant, message) VALUES('sc.sys.00010','sc','en','US','','Sign up using Facebook');
INSERT INTO bb_message(key, basename, language, country, variant, message) VALUES('sc.sys.00011','sc','en','US','','- OR -');
INSERT INTO bb_message(key, basename, language, country, variant, message) VALUES('sc.sys.00012','sc','en','US','','Full name');
INSERT INTO bb_message(key, basename, language, country, variant, message) VALUES('sc.sys.00013','sc','en','US','','Email');
INSERT INTO bb_message(key, basename, language, country, variant, message) VALUES('sc.sys.00014','sc','en','US','','Password');
INSERT INTO bb_message(key, basename, language, country, variant, message) VALUES('sc.sys.00015','sc','en','US','','Retype password');
INSERT INTO bb_message(key, basename, language, country, variant, message) VALUES('sc.sys.00016','sc','en','US','','I agree to the');
INSERT INTO bb_message(key, basename, language, country, variant, message) VALUES('sc.sys.00017','sc','en','US','','terms');
INSERT INTO bb_message(key, basename, language, country, variant, message) VALUES('sc.sys.00018','sc','en','US','','Sign up');
INSERT INTO bb_message(key, basename, language, country, variant, message) VALUES('sc.sys.00019','sc','en','US','','I already have a membership');
INSERT INTO bb_message(key, basename, language, country, variant, message) VALUES('sc.common.00001','sc','en','US','','New');
INSERT INTO bb_message(key, basename, language, country, variant, message) VALUES('sc.common.00001','sc','vi','VN','','Xin chào!');
INSERT INTO bb_message(key, basename, language, country, variant, message) VALUES('sc.common.00002','sc','en','US','','Edit');
INSERT INTO bb_message(key, basename, language, country, variant, message) VALUES('sc.common.00003','sc','en','US','','Delete');
INSERT INTO bb_message(key, basename, language, country, variant, message) VALUES('sc.common.00004','sc','en','US','','Search');
INSERT INTO bb_message(key, basename, language, country, variant, message) VALUES('sc.common.00005','sc','en','US','','List all');
INSERT INTO bb_message(key, basename, language, country, variant, message) VALUES('sc.common.00006','sc','en','US','','Search result');
INSERT INTO bb_message(key, basename, language, country, variant, message) VALUES('sc.common.00007','sc','en','US','','No.');
INSERT INTO bb_message(key, basename, language, country, variant, message) VALUES('sc.common.00008','sc','en','US','','Search information');
INSERT INTO bb_message(key, basename, language, country, variant, message) VALUES('sc.common.00009','sc','en','US','','Save');
INSERT INTO bb_message(key, basename, language, country, variant, message) VALUES('sc.common.00010','sc','en','US','','Edit form');
INSERT INTO bb_message(key, basename, language, country, variant, message) VALUES('sc.common.00011','sc','en','US','','Management');
INSERT INTO bb_message(key, basename, language, country, variant, message) VALUES('sc.navigationlink.00001','sc','en','US','','Navigation link');
INSERT INTO bb_message(key, basename, language, country, variant, message) VALUES('sc.navigationlink.00001','sc','vi','VN','','Xin chào!');
INSERT INTO bb_message(key, basename, language, country, variant, message) VALUES('sc.navigationlink.00002','sc','en','US','','Path');
INSERT INTO bb_message(key, basename, language, country, variant, message) VALUES('sc.message.00001','sc','en','US','','Message');
INSERT INTO bb_message(key, basename, language, country, variant, message) VALUES('sc.message.00001','sc','vi','VN','','Xin chào!');
INSERT INTO bb_message(key, basename, language, country, variant, message) VALUES('sc.message.00002','sc','en','US','','Search message');
INSERT INTO bb_message(key, basename, language, country, variant, message) VALUES('sc.message.00003','sc','en','US','','Message code');
INSERT INTO bb_message(key, basename, language, country, variant, message) VALUES('sc.account.00001','sc','en','US','','Account management');
INSERT INTO bb_message(key, basename, language, country, variant, message) VALUES('sc.account.00001','sc','vi','VN','','Xin chào!');
INSERT INTO bb_message(key, basename, language, country, variant, message) VALUES('sc.account.00002','sc','en','US','','Search account');
INSERT INTO bb_message(key, basename, language, country, variant, message) VALUES('sc.account.00003','sc','en','US','','Modify account');
INSERT INTO bb_message(key, basename, language, country, variant, message) VALUES('sc.account.00004','sc','en','US','','Delete account');
INSERT INTO bb_message(key, basename, language, country, variant, message) VALUES('sc.account.00005','sc','en','US','','Update account');
INSERT INTO bb_message(key, basename, language, country, variant, message) VALUES('sc.account.00006','sc','en','US','','User name');
INSERT INTO bb_message(key, basename, language, country, variant, message) VALUES('sc.account.00007','sc','en','US','','Password');
INSERT INTO bb_message(key, basename, language, country, variant, message) VALUES('sc.account.00008','sc','en','US','','Account none expired');
INSERT INTO bb_message(key, basename, language, country, variant, message) VALUES('sc.account.00009','sc','en','US','','Account none locked');
INSERT INTO bb_message(key, basename, language, country, variant, message) VALUES('sc.account.00010','sc','en','US','','Credentials none expired');
INSERT INTO bb_message(key, basename, language, country, variant, message) VALUES('sc.account.00011','sc','en','US','','Enabled');
INSERT INTO bb_message(key, basename, language, country, variant, message) VALUES('sc.account.00012','sc','en','US','','Account search result');